### PR TITLE
Rewrite run_ctest module in Java 11

### PR DESCRIPTION
**Pull request by CornDavid5**
## What does this pull request do?
Rewrite the `run_ctest` module in Java 11. The original version is written in Python.

## What changes were included in this pull request?
Rewrite the whole module from scratch, I preserve the original logic as much as I can. The rewritten version is under the `run-ctest` directory.

### CODE REVIEW

**Comment by Alex-Lian** [comment]
@CornDavid5  Thanks for the wonderful PR. 

The following are some ideas for improvement:
1. According to https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206, lines not ending in a newline character aren't considered actual lines. So it is better to add a new line to the end of every file.

2. The code review has very strict rules. It is necessary to check the code style using the command `mvn checkstyle:checkstyle`. And I got ~200 errors from the check-style report. @CornDavid5 Can you reduce it?

3. Is `-Dproject.path`  only support relative path? I tried to inject an absolute path but failed. Can you improve it to support both?

**Comment by tianyin** [comment]
This is a really exciting PR! Thank you for working on it, @CornDavid5 !!

**Comment by CornDavid5** [comment]
@Alex-Lian Thanks for the suggestions.

Based on your suggestions, I have updated the PR
1. all files should end with a new line now
2. based on the Sun's checkstyle guideline, I have refactored most of the code base, `mvn checkstyle:checkstyle` return 0 violation now
3. the project is natively support both relative and absolute path, I just specify the relative path in the README, because I think it may be how most of user will use it. The reason I think you fail to use the absolute path may be because the wording in the README is not clear. If testing a submodule, the `project.path` has to point to the specific module not the parent project. For example, for hadoop-common, use `.../hadoop/hadoop-common-project/hadoop-common`. I have updated the README file.

**Comment by tianyin** [comment]
@Alex-Lian could you review the PR again? I really hope we can merge it :)

**Comment by Alex-Lian** [comment]
@CornDavid5 Thanks for the improvement!

I checked 1 & 2 and the modification looks good to me.

I still have questions for 3:
I try to use `Dproject.path=~/hadoop/hadoop-common-project/hadoop-common` which is the absolute path. But it will return the error: `java.nio.file.NoSuchFileException: /home/lian7/openctest/core/run-ctest/~/hadoop/hadoop-common-project/hadoop-common/target/classes/ctest-injected.xml`

And I also question for the running result:
The command I used is ` mvn exec:java -q -Dproject.name=hadoop-common -Dproject.path=../../../hadoop/hadoop-common-project/hadoop-common -Dmapping.path=resources/supported/hadoop-common/param_unset_getter_map.json -Dconf.pairs=hadoop.security.crypto.cipher.suite=AES/CTR/Padding -Dtest.methods=org.apache.hadoop.crypto.TestCryptoStreams#testAvailable`, where the value `AES/CTR/Padding` is the wrong value so that the test should fail. But after I run the command, it tells me that the result is pass. Then I dig deeper to seek the reason. I found that you set the wrong injection path in this line: https://github.com/xlab-uiuc/openctest/pull/30/files#diff-29597e002a22a634827f7853f9b77490047164693d286896cbfbf4a5eae2fea1R63 .Please correct me if I am wrong :).

**Comment by CornDavid5** [comment]
@Alex-Lian interesting, the program works on my pc and laptop. I see you try to use a path from `~` folder, did you clone hadoop by yourself, or did you use the `setup` script in the project under the `run-ctest/resources/supported/hadoop-common`?

**Comment by Alex-Lian** [comment]
@CornDavid5 
In the original repo, the injection path is `classes/core-ctest.xml` https://github.com/xlab-uiuc/openctest/blob/main/core/ctest_const.py#L84, And in your code, the injection path is `classes/ctest-injected.xml` HadoopCommon.java line 63.

Please correct me if I am wrong.

**Comment by CornDavid5** [comment]
@Alex-Lian 
seems like java's Path library can only parse `.` and `..`, but not `~`. So for now the temporary fix is to manually check and replace, `projectPath.trim().replaceFirst("^~",System.getProperty("user.home"))`. This could work in Linux system, but I haven't test it in Mac or Windows. 

I cannot reproduce the second problem, I clone the repo in the same relative location as the one mentioned in your reply, and use the same command you used, and I get `Fail: 1`

**Comment by CornDavid5** [comment]
@Alex-Lian 
I see, I changed the file name from core-ctest.xml to ctest-injected.xml. The change reflects in my code and git patch. If you want me to keep the original naming, I can change them back.

**Comment by tianyin** [comment]
> And change the folder name from run-ctest to run_ctest_java.

@Alex-Lian why you want to mix everything (from Java and Python) into the same folder?

**Comment by CornDavid5** [comment]
@tianyin 
The original python version will be in the folder `run_ctest` and java version will be in the folder `run_ctest_java`

**Comment by Alex-Lian** [comment]
@tianyin Java version code and Python version code are in two different folders. 

Currently, Java version codes are in `run-ctest` folder and Python version codes are in `run_ctest` folder (these two folders are different), which is unclear to the users. So I ask @CornDavid5 to change the folder name from `run-ctest` to `run_ctest_java`. And I will also update the Python folder name to `run_ctest_python` after the merge.

**Comment by tianyin** [comment]
got it! thanks @Alex-Lian and @CornDavid5 !

**Comment by CornDavid5** [comment]
@Alex-Lian 
renaming done!
Also, I will create a new PR for supporting of `Cassandra` later this afternoon after you merge this PR.

**Comment by Alex-Lian** [comment]
Thanks for the wonderful PR @CornDavid5 !!!!

**Pull request merged**
